<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>EssSharp.Integration</AssemblyName>
    <RootNamespace>EssSharp.Integration</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="appsettings.local.json" Condition="Exists('appsettings.local.json')" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Scripts\MsSql\configure-db.sh" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Scripts\MsSql\healthcheck.sh" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Scripts\MsSql\setup.sql" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Scripts\MsSql\start-db.sh" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Testcontainers" Version="4.4.0" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.4.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EssSharp\EssSharp.csproj" />
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties />
    </VisualStudio>
  </ProjectExtensions>

</Project>
