/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EssSharp.Client.OpenAPIDateConverter;

namespace EssSharp.Model
{
    /// <summary>
    /// AppEncryption
    /// </summary>
    [DataContract(Name = "AppEncryption")]
    public partial class AppEncryption : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppEncryption" /> class.
        /// </summary>
        /// <param name="type">&lt;p&gt;The supported encryption type. The only supported value is &lt;code&gt;OCID&lt;/code&gt;, representing Oracle Vault key management.&lt;/p&gt;.</param>
        /// <param name="key">key.</param>
        /// <param name="vaultId">&lt;p&gt;Required for OCID encryption type. The OCID of the Oracle Vault in OCI.&lt;/p&gt;.</param>
        /// <param name="masterKeyId">&lt;p&gt;Required for OCID encryption type. The OCID of the Master Encryption Key (MEK) in the Oracle Vault in OCI.&lt;/p&gt;.</param>
        public AppEncryption(string type = default, List<byte[]> key = default, string vaultId = default, string masterKeyId = default)
        {
            this.Type = type;
            this.Key = key;
            this.VaultId = vaultId;
            this.MasterKeyId = masterKeyId;
        }

        /// <summary>
        /// &lt;p&gt;The supported encryption type. The only supported value is &lt;code&gt;OCID&lt;/code&gt;, representing Oracle Vault key management.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;The supported encryption type. The only supported value is &lt;code&gt;OCID&lt;/code&gt;, representing Oracle Vault key management.&lt;/p&gt;</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name = "key", EmitDefaultValue = false)]
        public List<byte[]> Key { get; set; }

        /// <summary>
        /// &lt;p&gt;Required for OCID encryption type. The OCID of the Oracle Vault in OCI.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;Required for OCID encryption type. The OCID of the Oracle Vault in OCI.&lt;/p&gt;</value>
        [DataMember(Name = "vaultId", EmitDefaultValue = false)]
        public string VaultId { get; set; }

        /// <summary>
        /// &lt;p&gt;Required for OCID encryption type. The OCID of the Master Encryption Key (MEK) in the Oracle Vault in OCI.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;Required for OCID encryption type. The OCID of the Master Encryption Key (MEK) in the Oracle Vault in OCI.&lt;/p&gt;</value>
        [DataMember(Name = "masterKeyId", EmitDefaultValue = false)]
        public string MasterKeyId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppEncryption {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  VaultId: ").Append(VaultId).Append("\n");
            sb.Append("  MasterKeyId: ").Append(MasterKeyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
