/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EssSharp.Client.OpenAPIDateConverter;

namespace EssSharp.Model
{
    /// <summary>
    /// Connection
    /// </summary>
    [DataContract(Name = "Connection")]
    public partial class Connection : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum FILE for value: FILE
            /// </summary>
            [EnumMember(Value = "FILE")]
            FILE = 1,

            /// <summary>
            /// Enum DB for value: DB
            /// </summary>
            [EnumMember(Value = "DB")]
            DB = 2,

            /// <summary>
            /// Enum ESSBASE for value: ESSBASE
            /// </summary>
            [EnumMember(Value = "ESSBASE")]
            ESSBASE = 3,

            /// <summary>
            /// Enum BI for value: BI
            /// </summary>
            [EnumMember(Value = "BI")]
            BI = 4,

            /// <summary>
            /// Enum AI for value: AI
            /// </summary>
            [EnumMember(Value = "AI")]
            AI = 5
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Defines Subtype
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SubtypeEnum
        {
            /// <summary>
            /// Enum TEMPLATE for value: TEMPLATE
            /// </summary>
            [EnumMember(Value = "TEMPLATE")]
            TEMPLATE = 1,

            /// <summary>
            /// Enum EXCELFILE for value: EXCELFILE
            /// </summary>
            [EnumMember(Value = "EXCELFILE")]
            EXCELFILE = 2,

            /// <summary>
            /// Enum DB for value: DB
            /// </summary>
            [EnumMember(Value = "DB")]
            DB = 3,

            /// <summary>
            /// Enum DELIMITEDFILE for value: DELIMITEDFILE
            /// </summary>
            [EnumMember(Value = "DELIMITEDFILE")]
            DELIMITEDFILE = 4,

            /// <summary>
            /// Enum FIXEDWIDTHFILE for value: FIXEDWIDTHFILE
            /// </summary>
            [EnumMember(Value = "FIXEDWIDTHFILE")]
            FIXEDWIDTHFILE = 5,

            /// <summary>
            /// Enum BI for value: BI
            /// </summary>
            [EnumMember(Value = "BI")]
            BI = 6,

            /// <summary>
            /// Enum ESSBASE for value: ESSBASE
            /// </summary>
            [EnumMember(Value = "ESSBASE")]
            ESSBASE = 7,

            /// <summary>
            /// Enum JDBC for value: JDBC
            /// </summary>
            [EnumMember(Value = "JDBC")]
            JDBC = 8,

            /// <summary>
            /// Enum SPARK for value: SPARK
            /// </summary>
            [EnumMember(Value = "SPARK")]
            SPARK = 9,

            /// <summary>
            /// Enum MSSQL for value: MS_SQL
            /// </summary>
            [EnumMember(Value = "MS_SQL")]
            MSSQL = 10,

            /// <summary>
            /// Enum MYSQL for value: MYSQL
            /// </summary>
            [EnumMember(Value = "MYSQL")]
            MYSQL = 11,

            /// <summary>
            /// Enum DB2 for value: DB2
            /// </summary>
            [EnumMember(Value = "DB2")]
            DB2 = 12,

            /// <summary>
            /// Enum ORACLE for value: ORACLE
            /// </summary>
            [EnumMember(Value = "ORACLE")]
            ORACLE = 13,

            /// <summary>
            /// Enum FILE for value: FILE
            /// </summary>
            [EnumMember(Value = "FILE")]
            FILE = 14,

            /// <summary>
            /// Enum AI for value: AI
            /// </summary>
            [EnumMember(Value = "AI")]
            AI = 15
        }


        /// <summary>
        /// Gets or Sets Subtype
        /// </summary>
        [DataMember(Name = "subtype", EmitDefaultValue = false)]
        public SubtypeEnum? Subtype { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Connection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Connection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Connection" /> class.
        /// </summary>
        /// <param name="description">description.</param>
        /// <param name="name">name (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="path">path.</param>
        /// <param name="catalog">catalog.</param>
        /// <param name="host">host.</param>
        /// <param name="port">port.</param>
        /// <param name="user">user.</param>
        /// <param name="password">password.</param>
        /// <param name="encrypted">encrypted.</param>
        /// <param name="token">token.</param>
        /// <param name="sid">sid.</param>
        /// <param name="service">service.</param>
        /// <param name="schema">schema.</param>
        /// <param name="dbURL">dbURL.</param>
        /// <param name="dbDriver">dbDriver.</param>
        /// <param name="datasource">datasource.</param>
        /// <param name="subtype">subtype.</param>
        /// <param name="walletPath">walletPath.</param>
        /// <param name="repoWallet">repoWallet.</param>
        /// <param name="minPoolSize">minPoolSize.</param>
        /// <param name="maxPoolSize">maxPoolSize.</param>
        /// <param name="hidden">hidden.</param>
        /// <param name="availability">availability.</param>
        /// <param name="aiConnection">aiConnection.</param>
        /// <param name="chatCredential">chatCredential.</param>
        /// <param name="vectorCredential">vectorCredential.</param>
        /// <param name="chatModel">chatModel.</param>
        /// <param name="ociCompartmentId">ociCompartmentId.</param>
        /// <param name="region">region.</param>
        /// <param name="url">url.</param>
        /// <param name="embedModel">embedModel.</param>
        /// <param name="transferTimeout">transferTimeout.</param>
        /// <param name="ociAPIFormat">ociAPIFormat (required).</param>
        /// <param name="narrateIndexName">narrateIndexName.</param>
        /// <param name="narrateProfileName">narrateProfileName.</param>
        /// <param name="narrateDocDirectory">narrateDocDirectory.</param>
        /// <param name="links">links.</param>
        public Connection(string description = default, string name = default, TypeEnum type = default, string path = default, bool catalog = default, string host = default, int port = default, string user = default, string password = default, bool encrypted = default, string token = default, string sid = default, string service = default, string schema = default, string dbURL = default, string dbDriver = default, string datasource = default, SubtypeEnum? subtype = default, string walletPath = default, bool repoWallet = default, int minPoolSize = default, int maxPoolSize = default, bool hidden = default, string availability = default, string aiConnection = default, string chatCredential = default, string vectorCredential = default, string chatModel = default, string ociCompartmentId = default, string region = default, string url = default, string embedModel = default, string transferTimeout = default, string ociAPIFormat = default, string narrateIndexName = default, string narrateProfileName = default, string narrateDocDirectory = default, List<Link> links = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for Connection and cannot be null");
            }
            this.Name = name;
            this.Type = type;
            // to ensure "ociAPIFormat" is required (not null)
            if (ociAPIFormat == null)
            {
                throw new ArgumentNullException("ociAPIFormat is a required property for Connection and cannot be null");
            }
            this.OciAPIFormat = ociAPIFormat;
            this.Description = description;
            this.Path = path;
            this.Catalog = catalog;
            this.Host = host;
            this.Port = port;
            this.User = user;
            this.Password = password;
            this.Encrypted = encrypted;
            this.Token = token;
            this.Sid = sid;
            this.Service = service;
            this.Schema = schema;
            this.DbURL = dbURL;
            this.DbDriver = dbDriver;
            this.Datasource = datasource;
            this.Subtype = subtype;
            this.WalletPath = walletPath;
            this.RepoWallet = repoWallet;
            this.MinPoolSize = minPoolSize;
            this.MaxPoolSize = maxPoolSize;
            this.Hidden = hidden;
            this.Availability = availability;
            this.AiConnection = aiConnection;
            this.ChatCredential = chatCredential;
            this.VectorCredential = vectorCredential;
            this.ChatModel = chatModel;
            this.OciCompartmentId = ociCompartmentId;
            this.Region = region;
            this.Url = url;
            this.EmbedModel = embedModel;
            this.TransferTimeout = transferTimeout;
            this.NarrateIndexName = narrateIndexName;
            this.NarrateProfileName = narrateProfileName;
            this.NarrateDocDirectory = narrateDocDirectory;
            this.Links = links;
        }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", EmitDefaultValue = false)]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets Catalog
        /// </summary>
        [DataMember(Name = "catalog", EmitDefaultValue = true)]
        public bool Catalog { get; set; }

        /// <summary>
        /// Gets or Sets Host
        /// </summary>
        [DataMember(Name = "host", EmitDefaultValue = false)]
        public string Host { get; set; }

        /// <summary>
        /// Gets or Sets Port
        /// </summary>
        [DataMember(Name = "port", EmitDefaultValue = false)]
        public int Port { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public string User { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", EmitDefaultValue = false)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets Encrypted
        /// </summary>
        [DataMember(Name = "encrypted", EmitDefaultValue = true)]
        public bool Encrypted { get; set; }

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// Gets or Sets Sid
        /// </summary>
        [DataMember(Name = "sid", EmitDefaultValue = false)]
        public string Sid { get; set; }

        /// <summary>
        /// Gets or Sets Service
        /// </summary>
        [DataMember(Name = "service", EmitDefaultValue = false)]
        public string Service { get; set; }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [DataMember(Name = "schema", EmitDefaultValue = false)]
        public string Schema { get; set; }

        /// <summary>
        /// Gets or Sets DbURL
        /// </summary>
        [DataMember(Name = "dbURL", EmitDefaultValue = false)]
        public string DbURL { get; set; }

        /// <summary>
        /// Gets or Sets DbDriver
        /// </summary>
        [DataMember(Name = "dbDriver", EmitDefaultValue = false)]
        public string DbDriver { get; set; }

        /// <summary>
        /// Gets or Sets Datasource
        /// </summary>
        [DataMember(Name = "datasource", EmitDefaultValue = false)]
        public string Datasource { get; set; }

        /// <summary>
        /// Gets or Sets WalletPath
        /// </summary>
        [DataMember(Name = "walletPath", EmitDefaultValue = false)]
        public string WalletPath { get; set; }

        /// <summary>
        /// Gets or Sets RepoWallet
        /// </summary>
        [DataMember(Name = "repoWallet", EmitDefaultValue = true)]
        public bool RepoWallet { get; set; }

        /// <summary>
        /// Gets or Sets MinPoolSize
        /// </summary>
        [DataMember(Name = "minPoolSize", EmitDefaultValue = false)]
        public int MinPoolSize { get; set; }

        /// <summary>
        /// Gets or Sets MaxPoolSize
        /// </summary>
        [DataMember(Name = "maxPoolSize", EmitDefaultValue = false)]
        public int MaxPoolSize { get; set; }

        /// <summary>
        /// Gets or Sets Hidden
        /// </summary>
        [DataMember(Name = "hidden", EmitDefaultValue = true)]
        public bool Hidden { get; set; }

        /// <summary>
        /// Gets or Sets Availability
        /// </summary>
        [DataMember(Name = "availability", EmitDefaultValue = false)]
        public string Availability { get; set; }

        /// <summary>
        /// Gets or Sets AiConnection
        /// </summary>
        [DataMember(Name = "aiConnection", EmitDefaultValue = false)]
        public string AiConnection { get; set; }

        /// <summary>
        /// Gets or Sets ChatCredential
        /// </summary>
        [DataMember(Name = "chatCredential", EmitDefaultValue = false)]
        public string ChatCredential { get; set; }

        /// <summary>
        /// Gets or Sets VectorCredential
        /// </summary>
        [DataMember(Name = "vectorCredential", EmitDefaultValue = false)]
        public string VectorCredential { get; set; }

        /// <summary>
        /// Gets or Sets ChatModel
        /// </summary>
        [DataMember(Name = "chatModel", EmitDefaultValue = false)]
        public string ChatModel { get; set; }

        /// <summary>
        /// Gets or Sets OciCompartmentId
        /// </summary>
        [DataMember(Name = "ociCompartmentId", EmitDefaultValue = false)]
        public string OciCompartmentId { get; set; }

        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        [DataMember(Name = "region", EmitDefaultValue = false)]
        public string Region { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets EmbedModel
        /// </summary>
        [DataMember(Name = "embedModel", EmitDefaultValue = false)]
        public string EmbedModel { get; set; }

        /// <summary>
        /// Gets or Sets TransferTimeout
        /// </summary>
        [DataMember(Name = "transferTimeout", EmitDefaultValue = false)]
        public string TransferTimeout { get; set; }

        /// <summary>
        /// Gets or Sets OciAPIFormat
        /// </summary>
        [DataMember(Name = "ociAPIFormat", IsRequired = true, EmitDefaultValue = true)]
        public string OciAPIFormat { get; set; }

        /// <summary>
        /// Gets or Sets NarrateIndexName
        /// </summary>
        [DataMember(Name = "narrateIndexName", EmitDefaultValue = false)]
        public string NarrateIndexName { get; set; }

        /// <summary>
        /// Gets or Sets NarrateProfileName
        /// </summary>
        [DataMember(Name = "narrateProfileName", EmitDefaultValue = false)]
        public string NarrateProfileName { get; set; }

        /// <summary>
        /// Gets or Sets NarrateDocDirectory
        /// </summary>
        [DataMember(Name = "narrateDocDirectory", EmitDefaultValue = false)]
        public string NarrateDocDirectory { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", EmitDefaultValue = false)]
        public List<Link> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Connection {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Catalog: ").Append(Catalog).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Encrypted: ").Append(Encrypted).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  Sid: ").Append(Sid).Append("\n");
            sb.Append("  Service: ").Append(Service).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("  DbURL: ").Append(DbURL).Append("\n");
            sb.Append("  DbDriver: ").Append(DbDriver).Append("\n");
            sb.Append("  Datasource: ").Append(Datasource).Append("\n");
            sb.Append("  Subtype: ").Append(Subtype).Append("\n");
            sb.Append("  WalletPath: ").Append(WalletPath).Append("\n");
            sb.Append("  RepoWallet: ").Append(RepoWallet).Append("\n");
            sb.Append("  MinPoolSize: ").Append(MinPoolSize).Append("\n");
            sb.Append("  MaxPoolSize: ").Append(MaxPoolSize).Append("\n");
            sb.Append("  Hidden: ").Append(Hidden).Append("\n");
            sb.Append("  Availability: ").Append(Availability).Append("\n");
            sb.Append("  AiConnection: ").Append(AiConnection).Append("\n");
            sb.Append("  ChatCredential: ").Append(ChatCredential).Append("\n");
            sb.Append("  VectorCredential: ").Append(VectorCredential).Append("\n");
            sb.Append("  ChatModel: ").Append(ChatModel).Append("\n");
            sb.Append("  OciCompartmentId: ").Append(OciCompartmentId).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  EmbedModel: ").Append(EmbedModel).Append("\n");
            sb.Append("  TransferTimeout: ").Append(TransferTimeout).Append("\n");
            sb.Append("  OciAPIFormat: ").Append(OciAPIFormat).Append("\n");
            sb.Append("  NarrateIndexName: ").Append(NarrateIndexName).Append("\n");
            sb.Append("  NarrateProfileName: ").Append(NarrateProfileName).Append("\n");
            sb.Append("  NarrateDocDirectory: ").Append(NarrateDocDirectory).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
