/*
 * REST API for Oracle Essbase
 *
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 2026.08.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EssSharp.Client.OpenAPIDateConverter;

namespace EssSharp.Model
{
    /// <summary>
    /// CreateApplication
    /// </summary>
    [DataContract(Name = "CreateApplication")]
    public partial class CreateApplication : IValidatableObject
    {
        /// <summary>
        /// Defines AppType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AppTypeEnum
        {
            /// <summary>
            /// Enum Native for value: native
            /// </summary>
            [EnumMember(Value = "native")]
            Native = 1,

            /// <summary>
            /// Enum Utf8 for value: utf8
            /// </summary>
            [EnumMember(Value = "utf8")]
            Utf8 = 2
        }


        /// <summary>
        /// Gets or Sets AppType
        /// </summary>
        [DataMember(Name = "appType", EmitDefaultValue = false)]
        public AppTypeEnum? AppType { get; set; }
        /// <summary>
        /// Defines DbType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DbTypeEnum
        {
            /// <summary>
            /// Enum NORMAL for value: NORMAL
            /// </summary>
            [EnumMember(Value = "NORMAL")]
            NORMAL = 1,

            /// <summary>
            /// Enum CURRENCY for value: CURRENCY
            /// </summary>
            [EnumMember(Value = "CURRENCY")]
            CURRENCY = 2,

            /// <summary>
            /// Enum ASO for value: ASO
            /// </summary>
            [EnumMember(Value = "ASO")]
            ASO = 3
        }


        /// <summary>
        /// Gets or Sets DbType
        /// </summary>
        [DataMember(Name = "dbType", EmitDefaultValue = false)]
        public DbTypeEnum? DbType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApplication" /> class.
        /// </summary>
        /// <param name="applicationName">&lt;p&gt;The application name must not exceed 30 characters. Avoid using spaces. Application names are not case-sensitive.&lt;/p&gt;.</param>
        /// <param name="databaseName">&lt;p&gt;The database (cube) name. The name is not case sensitive. Do not use spaces in the name. Only the following special characters are allowed in the name: &lt;code&gt;%$-{}()!~&#x60;#&amp;@^&lt;/code&gt;.&lt;/p&gt;.</param>
        /// <param name="allowDuplicates">&lt;p&gt;&lt;b&gt;true&lt;/b&gt; if duplicate member names are permitted. When you enable duplicate member names in an Essbase outline, then member names do not have to be unique. You can have multiple members using the same name in the outline.&lt;/p&gt;.</param>
        /// <param name="enableScenario">&lt;p&gt;&lt;b&gt;true&lt;/b&gt; if cubes can be enabled for scenario management. Note that scenario management is supported only for block storage cubes. For aggregate storage cubes, the only supported value for this parameter is &lt;b&gt;false&lt;/b&gt;.&lt;/p&gt;.</param>
        /// <param name="memberCount">memberCount.</param>
        /// <param name="databaseType">&lt;p&gt;The type of database (cube) to create. Values: &lt;b&gt;BSO&lt;/b&gt; for block storage cube, or &lt;b&gt;ASO&lt;/b&gt; for aggregate storage cube.&lt;/p&gt;.</param>
        /// <param name="memberPrefix">memberPrefix.</param>
        /// <param name="appType">appType.</param>
        /// <param name="dbType">dbType.</param>
        public CreateApplication(string applicationName = default, string databaseName = default, bool allowDuplicates = default, bool enableScenario = default, int memberCount = default, string databaseType = default, string memberPrefix = default, AppTypeEnum? appType = default, DbTypeEnum? dbType = default)
        {
            this.ApplicationName = applicationName;
            this.DatabaseName = databaseName;
            this.AllowDuplicates = allowDuplicates;
            this.EnableScenario = enableScenario;
            this.MemberCount = memberCount;
            this.DatabaseType = databaseType;
            this.MemberPrefix = memberPrefix;
            this.AppType = appType;
            this.DbType = dbType;
        }

        /// <summary>
        /// &lt;p&gt;The application name must not exceed 30 characters. Avoid using spaces. Application names are not case-sensitive.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;The application name must not exceed 30 characters. Avoid using spaces. Application names are not case-sensitive.&lt;/p&gt;</value>
        [DataMember(Name = "applicationName", EmitDefaultValue = false)]
        public string ApplicationName { get; set; }

        /// <summary>
        /// &lt;p&gt;The database (cube) name. The name is not case sensitive. Do not use spaces in the name. Only the following special characters are allowed in the name: &lt;code&gt;%$-{}()!~&#x60;#&amp;@^&lt;/code&gt;.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;The database (cube) name. The name is not case sensitive. Do not use spaces in the name. Only the following special characters are allowed in the name: &lt;code&gt;%$-{}()!~&#x60;#&amp;@^&lt;/code&gt;.&lt;/p&gt;</value>
        [DataMember(Name = "databaseName", EmitDefaultValue = false)]
        public string DatabaseName { get; set; }

        /// <summary>
        /// &lt;p&gt;&lt;b&gt;true&lt;/b&gt; if duplicate member names are permitted. When you enable duplicate member names in an Essbase outline, then member names do not have to be unique. You can have multiple members using the same name in the outline.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;&lt;b&gt;true&lt;/b&gt; if duplicate member names are permitted. When you enable duplicate member names in an Essbase outline, then member names do not have to be unique. You can have multiple members using the same name in the outline.&lt;/p&gt;</value>
        [DataMember(Name = "allowDuplicates", EmitDefaultValue = true)]
        public bool AllowDuplicates { get; set; }

        /// <summary>
        /// &lt;p&gt;&lt;b&gt;true&lt;/b&gt; if cubes can be enabled for scenario management. Note that scenario management is supported only for block storage cubes. For aggregate storage cubes, the only supported value for this parameter is &lt;b&gt;false&lt;/b&gt;.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;&lt;b&gt;true&lt;/b&gt; if cubes can be enabled for scenario management. Note that scenario management is supported only for block storage cubes. For aggregate storage cubes, the only supported value for this parameter is &lt;b&gt;false&lt;/b&gt;.&lt;/p&gt;</value>
        [DataMember(Name = "enableScenario", EmitDefaultValue = true)]
        public bool EnableScenario { get; set; }

        /// <summary>
        /// Gets or Sets MemberCount
        /// </summary>
        [DataMember(Name = "memberCount", EmitDefaultValue = false)]
        public int MemberCount { get; set; }

        /// <summary>
        /// &lt;p&gt;The type of database (cube) to create. Values: &lt;b&gt;BSO&lt;/b&gt; for block storage cube, or &lt;b&gt;ASO&lt;/b&gt; for aggregate storage cube.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;The type of database (cube) to create. Values: &lt;b&gt;BSO&lt;/b&gt; for block storage cube, or &lt;b&gt;ASO&lt;/b&gt; for aggregate storage cube.&lt;/p&gt;</value>
        [DataMember(Name = "databaseType", EmitDefaultValue = false)]
        public string DatabaseType { get; set; }

        /// <summary>
        /// Gets or Sets MemberPrefix
        /// </summary>
        [DataMember(Name = "memberPrefix", EmitDefaultValue = false)]
        public string MemberPrefix { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateApplication {\n");
            sb.Append("  ApplicationName: ").Append(ApplicationName).Append("\n");
            sb.Append("  DatabaseName: ").Append(DatabaseName).Append("\n");
            sb.Append("  AllowDuplicates: ").Append(AllowDuplicates).Append("\n");
            sb.Append("  EnableScenario: ").Append(EnableScenario).Append("\n");
            sb.Append("  MemberCount: ").Append(MemberCount).Append("\n");
            sb.Append("  DatabaseType: ").Append(DatabaseType).Append("\n");
            sb.Append("  MemberPrefix: ").Append(MemberPrefix).Append("\n");
            sb.Append("  AppType: ").Append(AppType).Append("\n");
            sb.Append("  DbType: ").Append(DbType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
