/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EssSharp.Client.OpenAPIDateConverter;

namespace EssSharp.Model
{
    /// <summary>
    /// DefaultLayoutBean
    /// </summary>
    [DataContract(Name = "DefaultLayoutBean")]
    public partial class DefaultLayoutBean : IEquatable<DefaultLayoutBean>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultLayoutBean" /> class.
        /// </summary>
        /// <param name="userDefault">userDefault.</param>
        /// <param name="databaseDefault">databaseDefault.</param>
        public DefaultLayoutBean(bool userDefault = default(bool), bool databaseDefault = default(bool))
        {
            this.UserDefault = userDefault;
            this.DatabaseDefault = databaseDefault;
        }

        /// <summary>
        /// Gets or Sets UserDefault
        /// </summary>
        [DataMember(Name = "userDefault", EmitDefaultValue = true)]
        public bool UserDefault { get; set; }

        /// <summary>
        /// Gets or Sets DatabaseDefault
        /// </summary>
        [DataMember(Name = "databaseDefault", EmitDefaultValue = true)]
        public bool DatabaseDefault { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DefaultLayoutBean {\n");
            sb.Append("  UserDefault: ").Append(UserDefault).Append("\n");
            sb.Append("  DatabaseDefault: ").Append(DatabaseDefault).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DefaultLayoutBean);
        }

        /// <summary>
        /// Returns true if DefaultLayoutBean instances are equal
        /// </summary>
        /// <param name="input">Instance of DefaultLayoutBean to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DefaultLayoutBean input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.UserDefault == input.UserDefault ||
                    this.UserDefault.Equals(input.UserDefault)
                ) && 
                (
                    this.DatabaseDefault == input.DatabaseDefault ||
                    this.DatabaseDefault.Equals(input.DatabaseDefault)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.UserDefault.GetHashCode();
                hashCode = (hashCode * 59) + this.DatabaseDefault.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
