/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EssSharp.Client.OpenAPIDateConverter;

namespace EssSharp.Model
{
    /// <summary>
    /// EssToDsMapDTO
    /// </summary>
    [DataContract(Name = "EssToDsMapDTO")]
    public partial class EssToDsMapDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EssToDsMapDTO" /> class.
        /// </summary>
        /// <param name="dimensions">dimensions.</param>
        /// <param name="pivotDimension">pivotDimension.</param>
        public EssToDsMapDTO(List<Dimension> dimensions = default, Dimension pivotDimension = default)
        {
            this.Dimensions = dimensions;
            this.PivotDimension = pivotDimension;
        }

        /// <summary>
        /// Gets or Sets Dimensions
        /// </summary>
        [DataMember(Name = "dimensions", EmitDefaultValue = false)]
        public List<Dimension> Dimensions { get; set; }

        /// <summary>
        /// Gets or Sets PivotDimension
        /// </summary>
        [DataMember(Name = "pivotDimension", EmitDefaultValue = false)]
        public Dimension PivotDimension { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EssToDsMapDTO {\n");
            sb.Append("  Dimensions: ").Append(Dimensions).Append("\n");
            sb.Append("  PivotDimension: ").Append(PivotDimension).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
