/*
 * REST API for Oracle Essbase
 *
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 2026.08.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EssSharp.Client.OpenAPIDateConverter;

namespace EssSharp.Model
{
    /// <summary>
    /// OCIVectorCredentialDTO
    /// </summary>
    [DataContract(Name = "OCIVectorCredentialDTO")]
    public partial class OCIVectorCredentialDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OCIVectorCredentialDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OCIVectorCredentialDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OCIVectorCredentialDTO" /> class.
        /// </summary>
        /// <param name="userOcid">userOcid (required).</param>
        /// <param name="tenancyOcid">tenancyOcid (required).</param>
        /// <param name="compartmentOcid">compartmentOcid (required).</param>
        /// <param name="privateKey">privateKey (required).</param>
        /// <param name="fingerprint">fingerprint (required).</param>
        /// <param name="url">url (required).</param>
        /// <param name="embedModel">embedModel (required).</param>
        public OCIVectorCredentialDTO(string userOcid = default, string tenancyOcid = default, string compartmentOcid = default, string privateKey = default, string fingerprint = default, string url = default, string embedModel = default)
        {
            // to ensure "userOcid" is required (not null)
            if (userOcid == null)
            {
                throw new ArgumentNullException("userOcid is a required property for OCIVectorCredentialDTO and cannot be null");
            }
            this.UserOcid = userOcid;
            // to ensure "tenancyOcid" is required (not null)
            if (tenancyOcid == null)
            {
                throw new ArgumentNullException("tenancyOcid is a required property for OCIVectorCredentialDTO and cannot be null");
            }
            this.TenancyOcid = tenancyOcid;
            // to ensure "compartmentOcid" is required (not null)
            if (compartmentOcid == null)
            {
                throw new ArgumentNullException("compartmentOcid is a required property for OCIVectorCredentialDTO and cannot be null");
            }
            this.CompartmentOcid = compartmentOcid;
            // to ensure "privateKey" is required (not null)
            if (privateKey == null)
            {
                throw new ArgumentNullException("privateKey is a required property for OCIVectorCredentialDTO and cannot be null");
            }
            this.PrivateKey = privateKey;
            // to ensure "fingerprint" is required (not null)
            if (fingerprint == null)
            {
                throw new ArgumentNullException("fingerprint is a required property for OCIVectorCredentialDTO and cannot be null");
            }
            this.Fingerprint = fingerprint;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for OCIVectorCredentialDTO and cannot be null");
            }
            this.Url = url;
            // to ensure "embedModel" is required (not null)
            if (embedModel == null)
            {
                throw new ArgumentNullException("embedModel is a required property for OCIVectorCredentialDTO and cannot be null");
            }
            this.EmbedModel = embedModel;
        }

        /// <summary>
        /// Gets or Sets UserOcid
        /// </summary>
        [DataMember(Name = "user_ocid", IsRequired = true, EmitDefaultValue = true)]
        public string UserOcid { get; set; }

        /// <summary>
        /// Gets or Sets TenancyOcid
        /// </summary>
        [DataMember(Name = "tenancy_ocid", IsRequired = true, EmitDefaultValue = true)]
        public string TenancyOcid { get; set; }

        /// <summary>
        /// Gets or Sets CompartmentOcid
        /// </summary>
        [DataMember(Name = "compartment_ocid", IsRequired = true, EmitDefaultValue = true)]
        public string CompartmentOcid { get; set; }

        /// <summary>
        /// Gets or Sets PrivateKey
        /// </summary>
        [DataMember(Name = "private_key", IsRequired = true, EmitDefaultValue = true)]
        public string PrivateKey { get; set; }

        /// <summary>
        /// Gets or Sets Fingerprint
        /// </summary>
        [DataMember(Name = "fingerprint", IsRequired = true, EmitDefaultValue = true)]
        public string Fingerprint { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets EmbedModel
        /// </summary>
        [DataMember(Name = "embed_model", IsRequired = true, EmitDefaultValue = true)]
        public string EmbedModel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OCIVectorCredentialDTO {\n");
            sb.Append("  UserOcid: ").Append(UserOcid).Append("\n");
            sb.Append("  TenancyOcid: ").Append(TenancyOcid).Append("\n");
            sb.Append("  CompartmentOcid: ").Append(CompartmentOcid).Append("\n");
            sb.Append("  PrivateKey: ").Append(PrivateKey).Append("\n");
            sb.Append("  Fingerprint: ").Append(Fingerprint).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  EmbedModel: ").Append(EmbedModel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
