/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EssSharp.Client.OpenAPIDateConverter;

namespace EssSharp.Model
{
    /// <summary>
    /// SystemMaintenanceLimits
    /// </summary>
    [DataContract(Name = "SystemMaintenanceLimits")]
    public partial class SystemMaintenanceLimits : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMaintenanceLimits" /> class.
        /// </summary>
        /// <param name="disk">disk.</param>
        /// <param name="ram">ram.</param>
        public SystemMaintenanceLimits(SystemMaintainableResource disk = default(SystemMaintainableResource), SystemMaintainableResource ram = default(SystemMaintainableResource))
        {
            this.Disk = disk;
            this.Ram = ram;
        }

        /// <summary>
        /// Gets or Sets Disk
        /// </summary>
        [DataMember(Name = "disk", EmitDefaultValue = false)]
        public SystemMaintainableResource Disk { get; set; }

        /// <summary>
        /// Gets or Sets Ram
        /// </summary>
        [DataMember(Name = "ram", EmitDefaultValue = false)]
        public SystemMaintainableResource Ram { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemMaintenanceLimits {\n");
            sb.Append("  Disk: ").Append(Disk).Append("\n");
            sb.Append("  Ram: ").Append(Ram).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
