/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing AppGeneralSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppGeneralSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppGeneralSettings
        //private AppGeneralSettings instance;

        public AppGeneralSettingsTests()
        {
            // TODO uncomment below to create an instance of AppGeneralSettings
            //instance = new AppGeneralSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppGeneralSettings
        /// </summary>
        [Fact]
        public void AppGeneralSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppGeneralSettings
            //Assert.IsType<AppGeneralSettings>(instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'LogLevelAsString'
        /// </summary>
        [Fact]
        public void LogLevelAsStringTest()
        {
            // TODO unit test for the property 'LogLevelAsString'
        }
        /// <summary>
        /// Test the property 'EasManagedApp'
        /// </summary>
        [Fact]
        public void EasManagedAppTest()
        {
            // TODO unit test for the property 'EasManagedApp'
        }
        /// <summary>
        /// Test the property 'TimeoutOnDataBlockLocks'
        /// </summary>
        [Fact]
        public void TimeoutOnDataBlockLocksTest()
        {
            // TODO unit test for the property 'TimeoutOnDataBlockLocks'
        }
        /// <summary>
        /// Test the property 'MaxAttachmentFileSizeInKbs'
        /// </summary>
        [Fact]
        public void MaxAttachmentFileSizeInKbsTest()
        {
            // TODO unit test for the property 'MaxAttachmentFileSizeInKbs'
        }
        /// <summary>
        /// Test the property 'PendingCacheSizeLimitInMbs'
        /// </summary>
        [Fact]
        public void PendingCacheSizeLimitInMbsTest()
        {
            // TODO unit test for the property 'PendingCacheSizeLimitInMbs'
        }

    }

}
