/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing AttributeOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttributeOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttributeOptions
        //private AttributeOptions instance;

        public AttributeOptionsTests()
        {
            // TODO uncomment below to create an instance of AttributeOptions
            //instance = new AttributeOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttributeOptions
        /// </summary>
        [Fact]
        public void AttributeOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AttributeOptions
            //Assert.IsType<AttributeOptions>(instance);
        }


        /// <summary>
        /// Test the property 'IndepDimensions'
        /// </summary>
        [Fact]
        public void IndepDimensionsTest()
        {
            // TODO unit test for the property 'IndepDimensions'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'BaseDimension'
        /// </summary>
        [Fact]
        public void BaseDimensionTest()
        {
            // TODO unit test for the property 'BaseDimension'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'ScadisAssociationMode'
        /// </summary>
        [Fact]
        public void ScadisAssociationModeTest()
        {
            // TODO unit test for the property 'ScadisAssociationMode'
        }
        /// <summary>
        /// Test the property 'ScaassociationMode'
        /// </summary>
        [Fact]
        public void ScaassociationModeTest()
        {
            // TODO unit test for the property 'ScaassociationMode'
        }

    }

}
