/*
 * REST API for Oracle Essbase
 *
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 2026.08.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CloudStorageDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloudStorageDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloudStorageDetails
        //private CloudStorageDetails instance;

        public CloudStorageDetailsTests()
        {
            // TODO uncomment below to create an instance of CloudStorageDetails
            //instance = new CloudStorageDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloudStorageDetails
        /// </summary>
        [Fact]
        public void CloudStorageDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CloudStorageDetails
            //Assert.IsType<CloudStorageDetails>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Fingerprint'
        /// </summary>
        [Fact]
        public void FingerprintTest()
        {
            // TODO unit test for the property 'Fingerprint'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }

        /// <summary>
        /// Test the property 'KeyContents'
        /// </summary>
        [Fact]
        public void KeyContentsTest()
        {
            // TODO unit test for the property 'KeyContents'
        }

        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Fact]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }

        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }

        /// <summary>
        /// Test the property 'Passphrase'
        /// </summary>
        [Fact]
        public void PassphraseTest()
        {
            // TODO unit test for the property 'Passphrase'
        }
    }
}
