/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ClusterNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClusterNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClusterNode
        //private ClusterNode instance;

        public ClusterNodeTests()
        {
            // TODO uncomment below to create an instance of ClusterNode
            //instance = new ClusterNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClusterNode
        /// </summary>
        [Fact]
        public void ClusterNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClusterNode
            //Assert.IsType<ClusterNode>(instance);
        }

        /// <summary>
        /// Test the property 'MachineName'
        /// </summary>
        [Fact]
        public void MachineNameTest()
        {
            // TODO unit test for the property 'MachineName'
        }

        /// <summary>
        /// Test the property 'AppName'
        /// </summary>
        [Fact]
        public void AppNameTest()
        {
            // TODO unit test for the property 'AppName'
        }

        /// <summary>
        /// Test the property 'DbName'
        /// </summary>
        [Fact]
        public void DbNameTest()
        {
            // TODO unit test for the property 'DbName'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'AgentUrl'
        /// </summary>
        [Fact]
        public void AgentUrlTest()
        {
            // TODO unit test for the property 'AgentUrl'
        }
    }
}
