/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ColumnSuppression
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ColumnSuppressionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ColumnSuppression
        //private ColumnSuppression instance;

        public ColumnSuppressionTests()
        {
            // TODO uncomment below to create an instance of ColumnSuppression
            //instance = new ColumnSuppression();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ColumnSuppression
        /// </summary>
        [Fact]
        public void ColumnSuppressionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ColumnSuppression
            //Assert.IsType<ColumnSuppression>(instance);
        }


        /// <summary>
        /// Test the property 'UnderScore'
        /// </summary>
        [Fact]
        public void UnderScoreTest()
        {
            // TODO unit test for the property 'UnderScore'
        }
        /// <summary>
        /// Test the property 'Derived'
        /// </summary>
        [Fact]
        public void DerivedTest()
        {
            // TODO unit test for the property 'Derived'
        }
        /// <summary>
        /// Test the property 'NoAccess'
        /// </summary>
        [Fact]
        public void NoAccessTest()
        {
            // TODO unit test for the property 'NoAccess'
        }
        /// <summary>
        /// Test the property 'EmptyBlocks'
        /// </summary>
        [Fact]
        public void EmptyBlocksTest()
        {
            // TODO unit test for the property 'EmptyBlocks'
        }
        /// <summary>
        /// Test the property 'Zero'
        /// </summary>
        [Fact]
        public void ZeroTest()
        {
            // TODO unit test for the property 'Zero'
        }
        /// <summary>
        /// Test the property 'Missing'
        /// </summary>
        [Fact]
        public void MissingTest()
        {
            // TODO unit test for the property 'Missing'
        }
        /// <summary>
        /// Test the property 'Invalid'
        /// </summary>
        [Fact]
        public void InvalidTest()
        {
            // TODO unit test for the property 'Invalid'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
