/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing Cube
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CubeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Cube
        //private Cube instance;

        public CubeTests()
        {
            // TODO uncomment below to create an instance of Cube
            //instance = new Cube();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Cube
        /// </summary>
        [Fact]
        public void CubeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Cube
            //Assert.IsType<Cube>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Fact]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Fact]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'ModifiedBy'
        /// </summary>
        [Fact]
        public void ModifiedByTest()
        {
            // TODO unit test for the property 'ModifiedBy'
        }
        /// <summary>
        /// Test the property 'ModifiedTime'
        /// </summary>
        [Fact]
        public void ModifiedTimeTest()
        {
            // TODO unit test for the property 'ModifiedTime'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ApplicationRole'
        /// </summary>
        [Fact]
        public void ApplicationRoleTest()
        {
            // TODO unit test for the property 'ApplicationRole'
        }
        /// <summary>
        /// Test the property 'EasManagedApp'
        /// </summary>
        [Fact]
        public void EasManagedAppTest()
        {
            // TODO unit test for the property 'EasManagedApp'
        }
        /// <summary>
        /// Test the property 'StartStopDBAllowed'
        /// </summary>
        [Fact]
        public void StartStopDBAllowedTest()
        {
            // TODO unit test for the property 'StartStopDBAllowed'
        }
        /// <summary>
        /// Test the property 'InspectDBAllowed'
        /// </summary>
        [Fact]
        public void InspectDBAllowedTest()
        {
            // TODO unit test for the property 'InspectDBAllowed'
        }
        /// <summary>
        /// Test the property 'DbVariablesSetting'
        /// </summary>
        [Fact]
        public void DbVariablesSettingTest()
        {
            // TODO unit test for the property 'DbVariablesSetting'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
