/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing DimensionMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DimensionMemberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DimensionMember
        //private DimensionMember instance;

        public DimensionMemberTests()
        {
            // TODO uncomment below to create an instance of DimensionMember
            //instance = new DimensionMember();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DimensionMember
        /// </summary>
        [Fact]
        public void DimensionMemberInstanceTest()
        {
            // TODO uncomment below to test "IsType" DimensionMember
            //Assert.IsType<DimensionMember>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NumberOfChildren'
        /// </summary>
        [Fact]
        public void NumberOfChildrenTest()
        {
            // TODO unit test for the property 'NumberOfChildren'
        }
        /// <summary>
        /// Test the property 'LevelNumber'
        /// </summary>
        [Fact]
        public void LevelNumberTest()
        {
            // TODO unit test for the property 'LevelNumber'
        }
        /// <summary>
        /// Test the property 'Aliases'
        /// </summary>
        [Fact]
        public void AliasesTest()
        {
            // TODO unit test for the property 'Aliases'
        }
        /// <summary>
        /// Test the property 'UniqueName'
        /// </summary>
        [Fact]
        public void UniqueNameTest()
        {
            // TODO unit test for the property 'UniqueName'
        }
        /// <summary>
        /// Test the property 'MemberId'
        /// </summary>
        [Fact]
        public void MemberIdTest()
        {
            // TODO unit test for the property 'MemberId'
        }
        /// <summary>
        /// Test the property 'PreviousSiblingsCount'
        /// </summary>
        [Fact]
        public void PreviousSiblingsCountTest()
        {
            // TODO unit test for the property 'PreviousSiblingsCount'
        }
        /// <summary>
        /// Test the property 'MemberSolveOrder'
        /// </summary>
        [Fact]
        public void MemberSolveOrderTest()
        {
            // TODO unit test for the property 'MemberSolveOrder'
        }
        /// <summary>
        /// Test the property 'DescentantsCount'
        /// </summary>
        [Fact]
        public void DescentantsCountTest()
        {
            // TODO unit test for the property 'DescentantsCount'
        }
        /// <summary>
        /// Test the property 'Dimension'
        /// </summary>
        [Fact]
        public void DimensionTest()
        {
            // TODO unit test for the property 'Dimension'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'DimSolveOrder'
        /// </summary>
        [Fact]
        public void DimSolveOrderTest()
        {
            // TODO unit test for the property 'DimSolveOrder'
        }
        /// <summary>
        /// Test the property 'DimensionType'
        /// </summary>
        [Fact]
        public void DimensionTypeTest()
        {
            // TODO unit test for the property 'DimensionType'
        }
        /// <summary>
        /// Test the property 'DataStorageType'
        /// </summary>
        [Fact]
        public void DataStorageTypeTest()
        {
            // TODO unit test for the property 'DataStorageType'
        }
        /// <summary>
        /// Test the property 'FormatString'
        /// </summary>
        [Fact]
        public void FormatStringTest()
        {
            // TODO unit test for the property 'FormatString'
        }
        /// <summary>
        /// Test the property 'DimStorageType'
        /// </summary>
        [Fact]
        public void DimStorageTypeTest()
        {
            // TODO unit test for the property 'DimStorageType'
        }
        /// <summary>
        /// Test the property 'CurrencyConversionCategory'
        /// </summary>
        [Fact]
        public void CurrencyConversionCategoryTest()
        {
            // TODO unit test for the property 'CurrencyConversionCategory'
        }

    }

}
