/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing DrillThroughRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DrillThroughRangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DrillThroughRange
        //private DrillThroughRange instance;

        public DrillThroughRangeTests()
        {
            // TODO uncomment below to create an instance of DrillThroughRange
            //instance = new DrillThroughRange();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DrillThroughRange
        /// </summary>
        [Fact]
        public void DrillThroughRangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" DrillThroughRange
            //Assert.IsType<DrillThroughRange>(instance);
        }


        /// <summary>
        /// Test the property 'Cells'
        /// </summary>
        [Fact]
        public void CellsTest()
        {
            // TODO unit test for the property 'Cells'
        }

    }

}
