/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing EssbaseInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EssbaseInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EssbaseInfo
        //private EssbaseInfo instance;

        public EssbaseInfoTests()
        {
            // TODO uncomment below to create an instance of EssbaseInfo
            //instance = new EssbaseInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EssbaseInfo
        /// </summary>
        [Fact]
        public void EssbaseInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EssbaseInfo
            //Assert.IsType<EssbaseInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Server'
        /// </summary>
        [Fact]
        public void ServerTest()
        {
            // TODO unit test for the property 'Server'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Fact]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property 'Database'
        /// </summary>
        [Fact]
        public void DatabaseTest()
        {
            // TODO unit test for the property 'Database'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
