/*
 * REST API for Oracle Essbase
 *
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 2026.08.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ExecuteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExecuteRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExecuteRequest
        //private ExecuteRequest instance;

        public ExecuteRequestTests()
        {
            // TODO uncomment below to create an instance of ExecuteRequest
            //instance = new ExecuteRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExecuteRequest
        /// </summary>
        [Fact]
        public void ExecuteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExecuteRequest
            //Assert.IsType<ExecuteRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Fact]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }

        /// <summary>
        /// Test the property 'CubeName'
        /// </summary>
        [Fact]
        public void CubeNameTest()
        {
            // TODO unit test for the property 'CubeName'
        }

        /// <summary>
        /// Test the property 'RecreateIfExists'
        /// </summary>
        [Fact]
        public void RecreateIfExistsTest()
        {
            // TODO unit test for the property 'RecreateIfExists'
        }

        /// <summary>
        /// Test the property 'SkipDataLoad'
        /// </summary>
        [Fact]
        public void SkipDataLoadTest()
        {
            // TODO unit test for the property 'SkipDataLoad'
        }

        /// <summary>
        /// Test the property 'DatabaseType'
        /// </summary>
        [Fact]
        public void DatabaseTypeTest()
        {
            // TODO unit test for the property 'DatabaseType'
        }

        /// <summary>
        /// Test the property 'SelectAiProfile'
        /// </summary>
        [Fact]
        public void SelectAiProfileTest()
        {
            // TODO unit test for the property 'SelectAiProfile'
        }

        /// <summary>
        /// Test the property 'ClientType'
        /// </summary>
        [Fact]
        public void ClientTypeTest()
        {
            // TODO unit test for the property 'ClientType'
        }

        /// <summary>
        /// Test the property 'EssbaseUrl'
        /// </summary>
        [Fact]
        public void EssbaseUrlTest()
        {
            // TODO unit test for the property 'EssbaseUrl'
        }

        /// <summary>
        /// Test the property 'EssbaseUser'
        /// </summary>
        [Fact]
        public void EssbaseUserTest()
        {
            // TODO unit test for the property 'EssbaseUser'
        }

        /// <summary>
        /// Test the property 'EssbasePassword'
        /// </summary>
        [Fact]
        public void EssbasePasswordTest()
        {
            // TODO unit test for the property 'EssbasePassword'
        }

        /// <summary>
        /// Test the property 'Columns'
        /// </summary>
        [Fact]
        public void ColumnsTest()
        {
            // TODO unit test for the property 'Columns'
        }

        /// <summary>
        /// Test the property 'CreateAnalyticView'
        /// </summary>
        [Fact]
        public void CreateAnalyticViewTest()
        {
            // TODO unit test for the property 'CreateAnalyticView'
        }

        /// <summary>
        /// Test the property 'AnalyticViewTargetSchema'
        /// </summary>
        [Fact]
        public void AnalyticViewTargetSchemaTest()
        {
            // TODO unit test for the property 'AnalyticViewTargetSchema'
        }

        /// <summary>
        /// Test the property 'CreateEssbaseCube'
        /// </summary>
        [Fact]
        public void CreateEssbaseCubeTest()
        {
            // TODO unit test for the property 'CreateEssbaseCube'
        }
    }
}
