/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GridRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridRangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridRange
        //private GridRange instance;

        public GridRangeTests()
        {
            // TODO uncomment below to create an instance of GridRange
            //instance = new GridRange();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridRange
        /// </summary>
        [Fact]
        public void GridRangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridRange
            //Assert.IsType<GridRange>(instance);
        }


        /// <summary>
        /// Test the property 'Statuses'
        /// </summary>
        [Fact]
        public void StatusesTest()
        {
            // TODO unit test for the property 'Statuses'
        }
        /// <summary>
        /// Test the property 'Texts'
        /// </summary>
        [Fact]
        public void TextsTest()
        {
            // TODO unit test for the property 'Texts'
        }
        /// <summary>
        /// Test the property 'EnumIds'
        /// </summary>
        [Fact]
        public void EnumIdsTest()
        {
            // TODO unit test for the property 'EnumIds'
        }
        /// <summary>
        /// Test the property 'DataFormats'
        /// </summary>
        [Fact]
        public void DataFormatsTest()
        {
            // TODO unit test for the property 'DataFormats'
        }
        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'Types'
        /// </summary>
        [Fact]
        public void TypesTest()
        {
            // TODO unit test for the property 'Types'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }

    }

}
