/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GridDimension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GridDimensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GridDimension
        //private GridDimension instance;

        public GridDimensionTests()
        {
            // TODO uncomment below to create an instance of GridDimension
            //instance = new GridDimension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GridDimension
        /// </summary>
        [Fact]
        public void GridDimensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" GridDimension
            //Assert.IsType<GridDimension>(instance);
        }


        /// <summary>
        /// Test the property 'Expanded'
        /// </summary>
        [Fact]
        public void ExpandedTest()
        {
            // TODO unit test for the property 'Expanded'
        }
        /// <summary>
        /// Test the property 'Pov'
        /// </summary>
        [Fact]
        public void PovTest()
        {
            // TODO unit test for the property 'Pov'
        }
        /// <summary>
        /// Test the property 'Column'
        /// </summary>
        [Fact]
        public void ColumnTest()
        {
            // TODO unit test for the property 'Column'
        }
        /// <summary>
        /// Test the property 'Row'
        /// </summary>
        [Fact]
        public void RowTest()
        {
            // TODO unit test for the property 'Row'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Fact]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
