/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ListLinkResponseObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListLinkResponseObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListLinkResponseObject
        //private ListLinkResponseObject instance;

        public ListLinkResponseObjectTests()
        {
            // TODO uncomment below to create an instance of ListLinkResponseObject
            //instance = new ListLinkResponseObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListLinkResponseObject
        /// </summary>
        [Fact]
        public void ListLinkResponseObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListLinkResponseObject
            //Assert.IsType<ListLinkResponseObject>(instance);
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
