/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing MDXOperation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MDXOperationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MDXOperation
        //private MDXOperation instance;

        public MDXOperationTests()
        {
            // TODO uncomment below to create an instance of MDXOperation
            //instance = new MDXOperation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MDXOperation
        /// </summary>
        [Fact]
        public void MDXOperationInstanceTest()
        {
            // TODO uncomment below to test "IsType" MDXOperation
            //Assert.IsType<MDXOperation>(instance);
        }


        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

    }

}
