/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ResetPasswordBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResetPasswordBeanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResetPasswordBean
        //private ResetPasswordBean instance;

        public ResetPasswordBeanTests()
        {
            // TODO uncomment below to create an instance of ResetPasswordBean
            //instance = new ResetPasswordBean();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResetPasswordBean
        /// </summary>
        [Fact]
        public void ResetPasswordBeanInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResetPasswordBean
            //Assert.IsType<ResetPasswordBean>(instance);
        }


        /// <summary>
        /// Test the property 'OldPassword'
        /// </summary>
        [Fact]
        public void OldPasswordTest()
        {
            // TODO unit test for the property 'OldPassword'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Fact]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }

    }

}
