/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing RoleBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RoleBeanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RoleBean
        //private RoleBean instance;

        public RoleBeanTests()
        {
            // TODO uncomment below to create an instance of RoleBean
            //instance = new RoleBean();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RoleBean
        /// </summary>
        [Fact]
        public void RoleBeanInstanceTest()
        {
            // TODO uncomment below to test "IsType" RoleBean
            //Assert.IsType<RoleBean>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'DefaultRole'
        /// </summary>
        [Fact]
        public void DefaultRoleTest()
        {
            // TODO unit test for the property 'DefaultRole'
        }

    }

}
