/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing SessionAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionAttributes
        //private SessionAttributes instance;

        public SessionAttributesTests()
        {
            // TODO uncomment below to create an instance of SessionAttributes
            //instance = new SessionAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionAttributes
        /// </summary>
        [Fact]
        public void SessionAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" SessionAttributes
            //Assert.IsType<SessionAttributes>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'LoginTimeInSeconds'
        /// </summary>
        [Fact]
        public void LoginTimeInSecondsTest()
        {
            // TODO unit test for the property 'LoginTimeInSeconds'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Fact]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property 'Database'
        /// </summary>
        [Fact]
        public void DatabaseTest()
        {
            // TODO unit test for the property 'Database'
        }
        /// <summary>
        /// Test the property 'DbConnectTimeInSeconds'
        /// </summary>
        [Fact]
        public void DbConnectTimeInSecondsTest()
        {
            // TODO unit test for the property 'DbConnectTimeInSeconds'
        }
        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Fact]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }
        /// <summary>
        /// Test the property 'RequestTimeInSeconds'
        /// </summary>
        [Fact]
        public void RequestTimeInSecondsTest()
        {
            // TODO unit test for the property 'RequestTimeInSeconds'
        }
        /// <summary>
        /// Test the property 'ConnectionSource'
        /// </summary>
        [Fact]
        public void ConnectionSourceTest()
        {
            // TODO unit test for the property 'ConnectionSource'
        }
        /// <summary>
        /// Test the property 'RequestState'
        /// </summary>
        [Fact]
        public void RequestStateTest()
        {
            // TODO unit test for the property 'RequestState'
        }

    }

}
