/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EssSharp.Api;
using EssSharp.Model;
using EssSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EssSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ShadowPromoteBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShadowPromoteBeanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShadowPromoteBean
        //private ShadowPromoteBean instance;

        public ShadowPromoteBeanTests()
        {
            // TODO uncomment below to create an instance of ShadowPromoteBean
            //instance = new ShadowPromoteBean();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShadowPromoteBean
        /// </summary>
        [Fact]
        public void ShadowPromoteBeanInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShadowPromoteBean
            //Assert.IsType<ShadowPromoteBean>(instance);
        }


        /// <summary>
        /// Test the property 'ShadowAppName'
        /// </summary>
        [Fact]
        public void ShadowAppNameTest()
        {
            // TODO unit test for the property 'ShadowAppName'
        }
        /// <summary>
        /// Test the property 'PrimaryAppName'
        /// </summary>
        [Fact]
        public void PrimaryAppNameTest()
        {
            // TODO unit test for the property 'PrimaryAppName'
        }
        /// <summary>
        /// Test the property 'TimeoutToForceUnloadApp'
        /// </summary>
        [Fact]
        public void TimeoutToForceUnloadAppTest()
        {
            // TODO unit test for the property 'TimeoutToForceUnloadApp'
        }
        /// <summary>
        /// Test the property 'RunInBackground'
        /// </summary>
        [Fact]
        public void RunInBackgroundTest()
        {
            // TODO unit test for the property 'RunInBackground'
        }

    }

}
