/*
 * The REST API for Oracle Essbase enables you to automate management of Essbase resources and operations. All requests and responses are communicated over secured HTTP.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EssSharp.Client;
using EssSharp.Api;
// uncomment below to import models
//using EssSharp.Model;

namespace EssSharp.Test.Api
{
    /// <summary>
    ///  Class for testing EmailApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailApiTests : IDisposable
    {
        private EmailApi instance;

        public EmailApiTests()
        {
            instance = new EmailApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailApi
            //Assert.IsType<EmailApi>(instance);
        }

        /// <summary>
        /// Test EmailAddIMAPDetails
        /// </summary>
        [Fact]
        public void EmailAddIMAPDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ServerConfiguration body = null;
            //var response = instance.EmailAddIMAPDetails(body);
            //Assert.IsType<ListLinkResponseObject>(response);
        }

        /// <summary>
        /// Test EmailAddSMTPDetails
        /// </summary>
        [Fact]
        public void EmailAddSMTPDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ServerConfiguration body = null;
            //var response = instance.EmailAddSMTPDetails(body);
            //Assert.IsType<ListLinkResponseObject>(response);
        }

        /// <summary>
        /// Test EmailDeleteIMAPDetails
        /// </summary>
        [Fact]
        public void EmailDeleteIMAPDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.EmailDeleteIMAPDetails();
        }

        /// <summary>
        /// Test EmailDeleteSMTPDetails
        /// </summary>
        [Fact]
        public void EmailDeleteSMTPDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.EmailDeleteSMTPDetails();
        }

        /// <summary>
        /// Test EmailGetEmailLinks
        /// </summary>
        [Fact]
        public void EmailGetEmailLinksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.EmailGetEmailLinks();
            //Assert.IsType<ListLinkResponseObject>(response);
        }

        /// <summary>
        /// Test EmailGetIMAPServerDetail
        /// </summary>
        [Fact]
        public void EmailGetIMAPServerDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.EmailGetIMAPServerDetail();
            //Assert.IsType<ServerConfiguration>(response);
        }

        /// <summary>
        /// Test EmailGetSMTPServerDetail
        /// </summary>
        [Fact]
        public void EmailGetSMTPServerDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.EmailGetSMTPServerDetail();
            //Assert.IsType<ServerConfiguration>(response);
        }
    }
}
