# This workflow will build and deploy the docfx project to GitHub Pages
# For more information see: https://dotnet.github.io/docfx/#publish-to-github-pages

name: Build / Publish Docs

on:
  workflow_dispatch:
  
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet tool update -g docfx
    - run: docfx docfx/docfx.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx/_site
